import os

PUBLIC_KEY = os.getenv("PUBLIC_KEY")
JWT_ISSUER = os.getenv("JWT_ISSUER")
JWT_AUDIENCE = os.getenv("JWT_AUDIENCE")
JWT_ALGORITHM = os.getenv("JWT_ALGORITHM")
DATABASE_PATH = os.getenv("DATABASE_PATH")